production:
  clients:
    default:
      uri: mongodb://heroku_lpfnlhmc:nc0sfc63e0sfnvepkcl6nctdgq@ds035806.mlab.com:35806/heroku_lpfnlhmc
development:
  clients:
    default:
      uri: mongodb://heroku_lpfnlhmc:nc0sfc63e0sfnvepkcl6nctdgq@ds035806.mlab.com:35806/heroku_lpfnlhmc
