# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 78ba73bf280d1d148747ab04875392c8ba90ffd74c617ed3a2be247bf08655aa0b7b6010b2057ff1176174b95306784a324945d2806ccf5fc45057b9ae617b37

test:
  secret_key_base: a2b119f69b4c706d303103399db465f49f1dfcf648a74f2867dea3b3cff722fb5674ca0ca9261284eafde5af6e0502c9a47db6750a7dee2dda9ac36266af8cf3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
